// JavaScript Document

var endereco_preenc = false,  cep_preenc = false, num_preenc = false, nome_preenc = false, sobrenome_preenc = false, email_preenc = false, cpf_preenc = false, confcpf_preenc = false, senha_preenc = false, confsenha_preenc = false, tel_preenc = false;
$(function(){var stylo_erro = {'background-color' : '#F00' , 'color' : '#FFF' , 'font-weight' : '700' }; var stylo_ok = {'background-color' : '#3F9' , 'color' : '#000' , 'font-weight' : '500' };  var aguardando_stylo = {"background-color" : "#FC6" , 'color' : '#000' , 'font-weight' : '500' }; $("#endereco").bind("keyup",
function(event) { var regex = /^[0-9a-z\u00C0-\u00ff A-Z \.\-\, ]+$/gi; if (regex.test($("#endereco").val()) == true) {$('#endereco').css(stylo_ok);endereco_preenc = true;} else { $('#endereco').css(stylo_erro); endereco_preenc = false;} atualizar_obrigat_preenc();}); $("#cep").bind("keyup",function(event) {var regex = /^[0-9]{5}-[0-9]{3}$/;if(this.value.length > 8 ){if (regex.test($("#cep").val()) == true) {$('#cep').css(stylo_ok);cep_preenc = true;} else {$('#cep').css(stylo_erro); cep_preenc = false;} }else{$('#cep').css(aguardando_stylo);cep_preenc = false; }
atualizar_obrigat_preenc();});$("#num").bind("keyup",function(event) {
var regex = /^[0-9.]+$/; if (regex.test($("#num").val()) == true) {num_preenc = true;  $('#num').css(stylo_ok); } else { $('#num').css(stylo_erro); num_preenc = false; } atualizar_obrigat_preenc();});$("#compl").bind("keyup",function(event) {if(this.value.length > 0 ){  var regex = /^[0-9a-z\u00C0-\u00ff A-Z \.\-\ ]+$/;  if (regex.test($("#compl").val()) == true) {  $('#compl').css(stylo_ok);  } else { $('#compl').css(stylo_erro); }}else{ $('#compl').css('background-color', '');} });$("#infoprox").bind("keyup", function(event) {if(this.value.length > 0 ){ var regex = /^[0-9a-z\u00C0-\u00ff A-Z]+$/;if (regex.test($("#infoprox").val()) == true) { $('#infoprox').css(stylo_ok);} else { $('#infoprox').css(stylo_erro);}}else{ $('#infoprox').css('background-color', '');} });$("#username").bind("keyup",function(event) { var regex = /^[a-z\u00C0-\u00ff\A-Z]+$/; if (regex.test($("#username").val()) == true) { nome_preenc = true;$('#username').css(stylo_ok); } else {$('#username').css(stylo_erro); nome_preenc = false; }atualizar_obrigat_preenc();});$("#usernamesobre").bind("keyup",function(event) {var regex = /^[a-z\u00C0-\u00ff\A-Z]+$/; if (regex.test($("#usernamesobre").val()) == true) {sobrenome_preenc = true;  $('#usernamesobre').css(stylo_ok);  } else { $('#usernamesobre').css(stylo_erro); sobrenome_preenc = false;}atualizar_obrigat_preenc();});var cpfeconfcpfeigual; $("#cpf").bind("keyup",function(event) {
 var regexum = /^(([0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}))$/; var regexdois = /^(([0-9]{3}.[0-9]{3}.[0-9]{3}-x{1}))$/; var regextres = /^(([0-9]{11}))$/;  
 if( regexum.test($("#cpf").val()) == true || regexdois.test($("#cpf").val()) == true || regextres.test($("#cpf").val()) == true ){cpf_preenc = true; }else{
 cpf_preenc = false;}if(regexum.test($("#cpf").val()) == true){ $('#cpf').css(stylo_ok);   }else if(regexdois.test($("#cpf").val()) == true){ $('#cpf').css(stylo_ok); }else if(regextres.test($("#cpf").val()) == true){$('#cpf').css(stylo_ok); }else{$('#cpf').css(aguardando_stylo); }comparecpf(); atualizar_obrigat_preenc();
});$("#confc").bind("keyup",function(event) {var regexum = /^(([0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}))$/;var regexdois = /^(([0-9]{3}.[0-9]{3}.[0-9]{3}-x{1}))$/;var regextres = /^(([0-9]{11}))$/; comparecpf();  if(regexum.test($("#confc").val()) == true  && cpfeconfcpfeigual === true){$('#confc').css(stylo_ok); }else
if(regexdois.test($("#confc").val()) == true &&  cpfeconfcpfeigual === true){ $('#confc').css(stylo_ok); }else if(regextres.test($("#confc").val()) == true && cpfeconfcpfeigual === true){ $('#confc').css(stylo_ok); }else{$('#confc').css(aguardando_stylo); } atualizar_obrigat_preenc();});function comparecpf() {
 var COMPARfo = document.getElementById('cpf').value;  var confc = document.getElementById('confc').value; if(confc == COMPARfo ){ if(confc.length > 0){ cpfeconfcpfeigual = true; confcpf_preenc = true;  $('#confc').css(stylo_ok); } }else{ cpfeconfcpfeigual = false;confcpf_preenc = false;  $('#confc').css(aguardando_stylo); }}$("#email").bind("keyup",function(event) { var regex = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;if(this.value.length > 0 ){ if (regex.test($("#email").val()) == true) { $('#email').css(stylo_ok); email_preenc = true;}else { $('#email').css(aguardando_stylo); email_preenc = false;} }else{email_preenc = false;} });var passeconfpasseigual;$("#password").bind("keyup", function(event) { var TAMAN = document.getElementById('password').value.length;if(TAMAN < 8){$('#password').css(aguardando_stylo); }else{ var regex = /(?=^.{8,12}$)(?=(?:.*?\d){2})(?=.*[a-z])(?=.*[A-Z])(?=(?:.*?[!@#$%*()_+^&}{:;?.]){2})(?!.*\s)[0-9a-zA-Z!@#$%*()_+^&]*$/ ;   
if (regex.test($("#password").val()) == true) {senha_preenc = true;  $('#password').css(stylo_ok);  } else {$('#password').css(stylo_erro);  senha_preenc = false; 
 } }comparepass(); atualizar_obrigat_preenc();}); $("#confirmpwd").bind("keyup",function(event) {var TAMAN = document.getElementById('confirmpwd').value.length;
comparepass();var regex = /(?=^.{8,12}$)(?=(?:.*?\d){2})(?=.*[a-z])(?=.*[A-Z])(?=(?:.*?[!@#$%*()_+^&}{:;?.]){2})(?!.*\s)[0-9a-zA-Z!@#$%*()_+^&]*$/ ;   
 if(TAMAN > 0){ if (regex.test($("#confirmpwd").val()) == true && passeconfpasseigual === true) {confsenha_preenc = true; 
 $('#confirmpwd').css(stylo_ok);  } else {$('#confirmpwd').css(aguardando_stylo);  confsenha_preenc = false; } }atualizar_obrigat_preenc();});
 function comparepass() { var COMPARfo = document.getElementById('password').value;  var confc = document.getElementById('confirmpwd').value; if(confc == COMPARfo){
 if(confc.length > 0){passeconfpasseigual = true; confsenha_preenc = true; $('#confirmpwd').css(stylo_ok);  } }else{ passeconfpasseigual = false;
confsenha_preenc = false;  $('#confirmpwd').css(aguardando_stylo); } }$("#tel").bind("keyup",function(event) {  var regex = /^(?:(?:\+|00)?(55)\s?)?(?:\(?([1-9][0-9])\)?\s?)?(?:((?:9\d|[2-9])\d{3})\-?(\d{4}))$/;if(this.value.length > 9  ){if (regex.test($("#tel").val()) == true) {$('#tel').css(stylo_ok); tel_preenc = true;}else { $('#tel').css(stylo_erro);tel_preenc = false;} }else{$('#tel').css(aguardando_stylo); tel_preenc = false;}atualizar_obrigat_preenc();});}); $(document).ready(function(e) {$('#anotei').hide();$('#MECADASTRAR').hide();var jaanotei;});var jafaleiqnaoatendem = false; var getlat,  getlong; function atualiz_coord_info(){ getlat = latcliente; getlong = longcliente; }function atualizar_obrigat_preenc(){jaanotei = false;if(endereco_preenc == true && cep_preenc == true && num_preenc == true && nome_preenc == true && sobrenome_preenc == true && email_preenc == true && cpf_preenc == true && confcpf_preenc == true &&  senha_preenc == true && confsenha_preenc == true && tel_preenc == true && jaanotei == false){if(Notcadastro == false){LIBERAR_button_anotar();}else{distancianaoatendida_jadis(); }
}else{$('#anotei').hide();}}function LIBERAR_button_anotar(){$('#anotei').show('fast');}function LIBERAR_button_submit(){jaanotei = true;
if(endereco_preenc == true && cep_preenc == true && num_preenc == true && nome_preenc == true && sobrenome_preenc == true && email_preenc == true && cpf_preenc == true && confcpf_preenc == true &&  senha_preenc == true && confsenha_preenc == true && tel_preenc == true && jaanotei == true && Notcadastro == false ){
	$("#info_anote_senha").hide();$('#anotei').hide('fast');$('#MECADASTRAR').show('fast');}}



